spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mp?rewriteBatchedStatements=true
    username: root
    password: javamysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: mengm
      password: mingtr

#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 输出日志
    # 枚举处理器
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-aliases-package: com.panyong.mp.domain.po
  mapper-locations: "classpath*:/mapper/**/*.xml"   # Mapper.xml 文件地址,默认值
  global-config:
    db-config:
      logic-delete-field: deleted   # 配置逻辑删除字段

logging:
  level:
    com.panyong: debug
  pattern:
    dateformat: HH:mm:ss

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      #生成文档所需的扫包路径，一般为启动类目录
#      packages-to-scan: com.panyong.mp.controller


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html  # 推荐的 Swagger UI 路径
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.panyong.mp.controller
  model-and-view-allowed: true

#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
#  basic:
#    enable: true
#    username: admin
#    password: 123456
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
    swagger-model-name: 用户模块
